[phases.setup]
nixPkgs = ['mysql80', 'pkg-config']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p staticfiles', 'python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3'
